# 프로덕션 환경 설정
spring:
  # 프로덕션 데이터베이스 (환경 변수 사용)
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/meetlog}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:7564}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

# 로깅 레벨 (프로덕션 환경)
logging:
  level:
    root: WARN
    com.meetlog: INFO
    org.springframework.web: INFO
    org.mybatis: WARN

# CORS 설정 (프로덕션 환경 - 실제 도메인만 허용)
cors:
  allowed-origins: https://yourdomain.com
  allowed-methods: GET,POST,PUT,DELETE,PATCH
  allowed-headers: "*"
  allow-credentials: true
